environment:
  env1:
    area_width: 30
    area_height: 15
    first_agent_pos: [3, 2]
    obstacles: []
    vertices:
      - [0, 0]
      - [30, 0]
      - [30, 15]
      - [0, 15]

  env2:
    area_width: 40
    area_height: 20
    first_agent_pos: [5, 5]
    obstacles: []
    vertices:
      - [5, 0]
      - [35, 0]
      - [40, 10]
      - [35, 20]
      - [5, 20]
      - [0, 10]
  
  env3:
    area_width: 40
    area_height: 20
    first_agent_pos: [7, 2]
    obstacles: []
    vertices:
      - [0, 0]
      - [40, 0]
      - [37, 12]
      - [27, 17]
      - [20, 20]
      - [8, 20]
      - [4, 14]

  env4:
    area_width: 35
    area_height: 15
    first_agent_pos: [3, 2]
    obstacles: 
      - [9, 4, 5, 4] 
      - [8, 10, 2, 3]
      - [14, 8, 4, 4]
    vertices:
      - [0, 0]
      - [35, 0]
      - [35, 15]
      - [0, 15]

  env5:
    area_width: 35
    area_height: 15
    first_agent_pos: [3, 2]
    obstacles: 
      - [9, 4, 5, 4]
      - [8, 10, 2, 3] 
      - [15, 8, 5, 3]
      - [30, 7, 4, 5]
    vertices:
      - [0, 0]
      - [35, 0]
      - [35, 15]
      - [0, 15]

  env6:
    area_width: 40
    area_height: 20
    first_agent_pos: [2, 6]
    obstacles:
      - [8, 7, 6, 1]
      - [8, 0, 1, 7]
      - [20, 7, 7, 1]
      - [22, 0, 1, 7]
      - [33, 7, 10, 1]
      - [8, 11, 5, 1]
      - [8, 11, 1, 9]
      - [18, 11, 12, 1]
      - [25, 11, 1, 9]
      - [35, 11, 5, 1]
    vertices:
      - [0, 0]
      - [40, 0]
      - [40, 20]
      - [0, 20]

simulation:
  scale: 40
  screen_size: [1600, 912]
  linewidth: 1
  total_time: 2000
  timestep: 1
  show_sensing_range: true
  show_goal: false
  show_connections: false
  show_trajectories: false

experiments:
  res_dir: "results"

agents:
  controller: "hexagon"
  original_method: true
  num_agents: 30
  agent_size: 0.2
  v_max: 0.1
  tolerance: 0.1
  sensing_range: 5.0
  communication_range: 2.5
  critical_ratio: 0.75
  avoidance_range: 0.05
  rho: 1.0
  pso_num_iterations: 100
  pso_num_particles: 50
  pso_weights: [1, 1, 1]
  path_planner:
    kg: 5
    ko: 0.0
    kc: 0.0
    beta_c: 1
